### ISSUE TITLE
I still receives embeds from other bots

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#124]
I still receives embeds from other bots, so I assume that it's not closed by discord:
![image](https://user-images.githubusercontent.com/89306625/151174977-6b6a6be9-0826-4302-8dcd-e02bb5d906b1.png)
![image](https://user-images.githubusercontent.com/89306625/151175074-30f2963e-5a54-41aa-ab98-501afd64b033.png)

**Comment by V4NSH4J** [comment]
I've explained this a bunch of times in detail. This is not the same embed as before. Consider the case when you send a YouTube video on discord, you can see it's thumbnail, this is because the link gets embedded but it's not an embed that you sent in payload like before. What these guys have done is they've added metadata (<meta>) to their website which they are sending in the message content so it embeds like that. In the second image you can see the link in the content, if you copy paste the link on its own alone, it would embed like that.  In the first image they've used Zero width space (U+200B) to hide the link (although it is still there if you look at the message object) I've provided an even more detailed explanation for this along with an example message which was sent in our guilded server's general chat the day embeds for userbots were patched.

**Comment by songbaizhi** [comment]
Hi, bro! Can you tell me how to make the URL ‘U+200B’?

**Comment by V4NSH4J** [comment]
> Hi, bro! Can you tell me how to make the URL ‘U+200B’?

I've explained it well enough for you to implement it. I have no interest in enabling people to send links like that.

**Comment by songbaizhi** [comment]
Thank you,I already know how to use it, thank you very much, okay
