### ISSUE TITLE
Is websocket making useful for DMing?

### ISSUE THREAD

**Issue by CssHammer** [V4NSH4J/discord-mass-DM-GO#138]
I'm wondering if online_tokens feature impacts token life somehow? Someone in the issues told that his tokens got locked and @V4NSH4J proposed to turn WS off

**Comment by V4NSH4J** [comment]
> I'm wondering if online_tokens feature impacts token life somehow? Someone in the issues told that his tokens got locked and @V4NSH4J proposed to turn WS off 

It doesn't, actually it can't lock them. But the feature is unstable which is why it's turned off by default and I don't really recommend having it on unless you want to use any function which requires it. To online your tokens for 400 Unauthorised error you can use the token onliner as a seperate option
