### ISSUE TITLE
Tokens problem

### ISSUE THREAD

**Issue by jhnsnow999** [V4NSH4J/discord-mass-DM-GO#156]
Does anyone know a good token seller ?

**Comment by V4NSH4J** [comment]
Not really, token market is dry right now. You'll only find overpriced tokens

**Comment by franklin112** [comment]
Any idea why al the token generators have problems? Has Discord done a patch or something

**Comment by V4NSH4J** [comment]
> Any idea why al the token generators have problems? Has Discord done a patch or something

Discord didn't really change much, I'm surprised why people didn't figure out what's wrong already

**Comment by franklin112** [comment]
i tried to find out, but can't really find a issue, however a lot of tokens with custom domains got banned.

**Comment by jerlam06** [comment]
I have been investigating a lot these past few days in order to find a way to generate tokens in mass, and I found out that 100% of my generated tokens require phone verification probably because of proxies and VPNs used to generate them. I believe discord has an insane list of 'blacklisted' proxies, and since VPNs' IP addresses are public, it is very easy for them to keep a blacklist too.
The only way to get past that is to get the accounts (tokens) phone validated using online services for temporary phone numbers, and since the price for a single SMS costs something between $0.15 and $1 it can quickly become costy...

**Comment by V4NSH4J** [comment]
> I have been investigating a lot these past few days in order to find a way to generate tokens in mass, and I found out that 100% of my generated tokens require phone verification probably because of proxies and VPNs used to generate them. I believe discord has an insane list of 'blacklisted' proxies, and since VPNs' IP addresses are public, it is very easy for them to keep a blacklist too. The only way to get past that is to get the accounts (tokens) phone validated using online services for temporary phone numbers, and since the price for a single SMS costs something between $0.15 and $1 it can quickly become costy...

Hey, discord does have an insane list of blacklisted proxies but if you buy good proxies you won't have to worry about that... While generating accounts, usually every flag counts towards the quality. If they're locked at generation, and you phone verify them you even stand a chance of disabling them....

**Comment by G4meFreak** [comment]
Is there still no working generator?

**Comment by franklin112** [comment]
There are, just watch out because a lot sell invalid tokens these days

**Comment by V4NSH4J** [comment]
Yeah, don't worry the market should be good again as always soon 
https://t.me/tosviolators
