### ISSUE TITLE
suggestion ><

### ISSUE THREAD

**Issue by qizq1337** [V4NSH4J/discord-mass-DM-GO#171]
make a full scraper, so it scrapes both offline and online lol :v

**Comment by V4NSH4J** [comment]
The names are kinda misleading. Online scraper can also scrape offline members if they're visible in the memberlist of the channel you're trying to scrape. Offline scraper can also scrape online members. Both use different methods, offline scraper would try to get most of the server using query brute which would include many online members as well. I wouldn't combine reaction scraper and online scraper yeah? Because they're completely different methods of scraping and I put it upto the user to use whichever one they want
