### ISSUE TITLE
waiting for perfect work, using 1.8.3 but still not working......

### ISSUE THREAD

**Issue by john1122334455** [V4NSH4J/discord-mass-DM-GO#350]
we are waiting for the perfect work but why not working perfectly? always getting error . now captcha error even i am using anti captcha service .
![captcha problem](https://user-images.githubusercontent.com/99329787/155833610-37acd186-616d-4823-8843-461f867dce78.png)

**Comment by V4NSH4J** [comment]
This new sitekey which you're getting doesn't get solved even after solving the captcha, it just gives captcha again.

**Comment by V4NSH4J** [comment]
I've recorded a quick video to demonstrate what is happening because many people are asking me this.
https://youtu.be/Xk7cP9hotnM
Watch this, I have this account which gives this sitekey as well, I try to join servers with it but it doesn't join me to the server and just gives another captcha. (Manually that is, without the program)
It's a glitch with discord's new sitekey and you'd just have to get tokens which don't give you this one. 
I can't really fix something that's not my program's problem. Watch the video, it's evident that it's something for Discord.
