### ISSUE TITLE
2Captcha loop

### ISSUE THREAD

**Issue by pixelartnft1** [V4NSH4J/discord-mass-DM-GO#363]
![image](https://user-images.githubusercontent.com/100177238/155986643-17505592-1913-4291-84c0-58b85ab06343.png)
Anywork around for this looping error using 2captcha?

**Comment by V4NSH4J** [comment]
Hey unfortuantely discord has been giving this particular Hcaptcha when they think the account is suspicious. It looks something like this on the client:
https://youtu.be/Xk7cP9hotnM
As you can see, I join the server but it gives me the captcha again. Hence why the program also loops infinitely.
If you're on DMDGO V1.8.2 or V1.8.3, I highly recommend updating to V1.8.4, as it was made so that it will respect the maximum invite rejoins set in config and also try to prevent this particular Hcaptcha in the first place

**Comment by xBytez5636** [comment]
1.8.4>1.8.5? 1.8.5 also has this.

**Comment by V4NSH4J** [comment]
1.8.4 and 1.8.5 are the same, 1.8.5 just has more captcha services, I said 1.8.4 because that's the latest release, release for 1.8.5 isn't out yet, it's only in the source code

**Comment by pixelartnft1** [comment]
I found the best way to get around this (as recommended) with a different source for tokens - works alot better!  Thanks @V4NSH4J!
