### ISSUE TITLE
400 when dming

### ISSUE THREAD

**Issue by ganynmednet** [V4NSH4J/discord-mass-DM-GO#458]
Just started receiving strange 400 in all servers

![image](https://user-images.githubusercontent.com/51125243/161128719-27f53ae8-3ab2-4791-add9-221b11abf783.png)

**Comment by ChronoBrake** [comment]
New Discord update. You need resolve Captcha when you wanna send DM

**Comment by tawainnumber2** [comment]
same here. i tried sending captcha with request but got another captcha response.

i also tried manually sending a DM through a web browser, and still was unable to send a DM. The captchas are very buggy. It opens 3 captchas at once. When you solve the captcha, the message still doesn't get sent. You get a response saying that you cannot DM this user, which is false, because i know i can DM this person.

**Comment by ganynmednet** [comment]
after the latest update can do in avg 10 dms instead of 30. Any thoughts on this?

**Comment by LongTomForever** [comment]
> after the latest update can do in avg 10 dms instead of 30. Any thoughts on this?

How do you manage to enter with tokens, I do not pass the captcha.

As for the 10 DM, this is most likely the internal restrictions of the discord, it all depends on the quality of the account - with confirmation by SMS, I also had 50 DM before.

**Comment by ganynmednet** [comment]
I think Captcha is the proxy- and token- related issue. My observation is that yesterday they required captcha before the first DM, today the allow you to send 10 dms before the captcha request. @V4NSH4J

**Comment by V4NSH4J** [comment]
> I think Captcha is the proxy- and token- related issue. My observation is that yesterday they required captcha before the first DM, today the allow you to send 10 dms before the captcha request. @V4NSH4J

Interesting 
#465 captchas on DMs are currently bypassed completely with DMDGO V1.8.8 It will work till discord patches it.
