### ISSUE TITLE
Embed code made from https://discohook.org/ does not work in message.json!

### ISSUE THREAD

**Issue by pycogenic** [V4NSH4J/discord-mass-DM-GO#575]

**Comment by V4NSH4J** [comment]
Hey, You can no longer send regular embeds like you used to before. A Discord patch made it so that only actual bots could do that now. 
However you can still send website embeds, this is when you send a link in your message and the link embeds into an Embed. A quick example of this is when you send a YouTube video on a discord chat, you can see the thumbnail there. This is because the thumbnail is embedded. 
You can use the feature recently added by @itschasa into DMDGO. You can input your information into embed.json and run the option on DMDGO to create a link for it. And put that link somewhere in the message content of your message.json. This way you will still be sending an embed.

**Comment by pycogenic** [comment]
Vansh
Thank you so much for taking the time to respond in so detail.
I must say you are doing a great job. You are a brilliant programmer as well as you are really good at building up an active community!
Keep it up bro :)

**Comment by V4NSH4J** [comment]
Thank you for your kind words! Feel free to re-open if you have any questions left!
