### ISSUE TITLE
Error while Unmarshalling incoming websocket message: json: cannot unmarshal array into Go struct field

### ISSUE THREAD

**Issue by tamtamb** [V4NSH4J/discord-mass-DM-GO#671]
Getting this error on DM on react:

Error while Unmarshalling incoming websocket message: json: cannot unmarshal array into Go struct field Data.d.threads of type bool {"t":"THREAD_LIST_SYNC","s":3,"op":0,"d":{"threads":[],"most_recent_messages":[],"guild_id":"93000000000000"}}

Error while Unmarshalling incoming websocket message: json: cannot unmarshal array into Go struct field Event.d of type instance.Data {"t":"SESSIONS_REPLACE","s":4,"op":0,"d":[{"status":"online","session_id":"c807310000000000000000","client_info":{"version":0,"os":"windows","client":"web"},"activities":[]}]}

![DMGO error](https://user-images.githubusercontent.com/104692079/170975879-90e37b0f-163b-4eb4-aff8-8147099ba4c0.png)

**Comment by mbmaali** [comment]
getting a similar error with auto react.

**Comment by V4NSH4J** [comment]
You may ignore this error, the way we access values from JSON in DMDGO is by making it a pre-determined type and then unmarshalling the JSON response to it. The pre-determined type was defined in order to use all the required information from Discord. So when discord sends something that DMDGO does not need, and hence the pre-determined type hasn't accommodated it, it gives a unmarshalling error. 

This particular error can be completely ignored and does not affect any performance. The only reason it logs in the first place is so that if there's a problem with the required system, it can be debugged.
