### ISSUE TITLE
tokens joining

### ISSUE THREAD

**Issue by bdkw** [V4NSH4J/discord-mass-DM-GO#8]
tokens joiner in starting not works it shows token is joined but while dming it shows 400 error.

**Comment by V4NSH4J** [comment]
Hey, error 400 means "bad request" and happens when there's a problem with the data on our end.
It could mean a lot of things:-
1) Format of your tokens is wrong (needs to be 1 on each line)
2) Format of your MemberIDs is wrong (needs to be 1 on each line)
3) The token tried to DM itself 
4) MemberIDs/tokens have blank lines
There are a LOT of places where you could go wrong and would get an error 400. If you want me to take a closer look, join the support server and find V4NSH4J
