### ISSUE TITLE
a few issues │fetch onlines only, reorder options, auto join check, profiles

### ISSUE THREAD

**Issue by trial-coder** [V4NSH4J/discord-mass-DM-GO#80]
hi first thanks for this awesome tool

not sure i can log more than one issue in one, but here it is

-the online fetching seem to fetch all even offline it would be great to fetch all statuses except offline, no?

-even if fetch all would be great to only dm onlines (and away, etc), but not offline

-would be good to options are in order we use them like 1) join 2) react 3) scrape 4) massdm ... something like that that is the workflow most would use so you dont miss a step

-include a test run option with only one token even if many in the token file so that you know quickly if everything works

-wait 5 seconds and automatically do option 13 after the join - since the tool already knows the server id from the invite

-do a profile where after "fetch" and "join" you could say "save as profile-xyz" to token.txt and memberids.txt get renamed "profile-xyz" and have like option to load a profile so that you can associate specific tokens to specific servers/memberids

these are just small examples of enhancements i have full of them in mind

and again, you are a world-class master coder

i will consider donate if i can get it to works proper (with good tokens and proxy) because now i paid for crapy tool and i am in the red :(

**Comment by keepstriving01** [comment]
@V4NSH4J bruh, your discord stopped working again?

**Comment by V4NSH4J** [comment]
> hi first thanks for this awesome tool
> 
> not sure i can log more than one issue in one, but here it is
> 
> -the online fetching seem to fetch all even offline it would be great to fetch all statuses except offline, no?
> 
> -even if fetch all would be great to only dm onlines (and away, etc), but not offline
> 
> -would be good to options are in order we use them like 1) join 2) react 3) scrape 4) massdm ... something like that that is the workflow most would use so you dont miss a step
> 
> -include a test run option with only one token even if many in the token file so that you know quickly if everything works
> 
> -wait 5 seconds and automatically do option 13 after the join - since the tool already knows the server id from the invite
> 
> -do a profile where after "fetch" and "join" you could say "save as profile-xyz" to token.txt and memberids.txt get renamed "profile-xyz" and have like option to load a profile so that you can associate specific tokens to specific servers/memberids
> 
> these are just small examples of enhancements i have full of them in mind
> 
> and again, you are a world-class master coder
> 
> i will consider donate if i can get it to works proper (with good tokens and proxy) because now i paid for crapy tool and i am in the red :(

The pleasure is mine. The online scraper fetches everyone who is visible in the memberlist. It's called an online scraper because in most cases it only scrapes online members. It is possible on some servers it scrapes offline users as well but most users of the program aim to scrape the maximum number of users. It may be possible that you're able to manually remove the offline ones from the list as they'd be towards the bottom. 

The order suggestion is very good, I will implement it. On a side note, you don't need to react to emoji to send DMs.

I can make something which would allow you to chose the number of tokens. I think that would solve this as well. 

This is possible too and can be incorporated in option 13, but option 13 can't be incorporated in invite joiner as some people use the tool only for joining tokens. Also with the serverid, we could only use the offline scraper (Misleading name: Fetches everyone it can which includes offline people but may also include online people)

Don't understand what these profiles mean, elaborate it a bit!

Thank you for your kind words :) If you have any difficulties, feel free to reach out. Let's get you back to the green! 




> @V4NSH4J bruh, your discord stopped working again?

Yes I got banned again, New discord is V6NSH4J#1511
